version: '3'
services:
  postgres:
    image: postgres:16
    container_name: recycla-db
    env_file:
      - ../env/db-env.env
    ports:
      - "5430:5432"
    volumes:
      - /Users/admin/Desktop/DB/recycla:/var/lib/postgresql/data